USE sakila;
-- Automatically generated by Advanced ETl Processor
-- http://www.etl-tools.com/
-- table language
-- Start of script
Insert into language
 (`language_id`,`name`,`last_update`)
Values
('1','English','2006-02-15 05:02:19.000')
;
Insert into language
 (`language_id`,`name`,`last_update`)
Values
('2','Italian','2006-02-15 05:02:19.000')
;
Insert into language
 (`language_id`,`name`,`last_update`)
Values
('3','Japanese','2006-02-15 05:02:19.000')
;
Insert into language
 (`language_id`,`name`,`last_update`)
Values
('4','Mandarin','2006-02-15 05:02:19.000')
;
Insert into language
 (`language_id`,`name`,`last_update`)
Values
('5','French','2006-02-15 05:02:19.000')
;
Insert into language
 (`language_id`,`name`,`last_update`)
Values
('6','German','2006-02-15 05:02:19.000')
;
-- End of Script
--
--