USE sakila;
-- Automatically generated by Advanced ETl Processor
-- http://www.etl-tools.com/
-- table country
-- Start of script
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('1','Afghanistan','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('2','Algeria','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('3','American Samoa','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('4','Angola','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('5','Anguilla','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('6','Argentina','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('7','Armenia','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('8','Australia','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('9','Austria','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('10','Azerbaijan','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('11','Bahrain','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('12','Bangladesh','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('13','Belarus','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('14','Bolivia','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('15','Brazil','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('16','Brunei','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('17','Bulgaria','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('18','Cambodia','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('19','Cameroon','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('20','Canada','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('21','Chad','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('22','Chile','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('23','China','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('24','Colombia','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('25','Congo, The Democratic Republic of the','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('26','Czech Republic','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('27','Dominican Republic','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('28','Ecuador','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('29','Egypt','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('30','Estonia','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('31','Ethiopia','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('32','Faroe Islands','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('33','Finland','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('34','France','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('35','French Guiana','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('36','French Polynesia','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('37','Gambia','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('38','Germany','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('39','Greece','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('40','Greenland','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('41','Holy See (Vatican City State)','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('42','Hong Kong','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('43','Hungary','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('44','India','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('45','Indonesia','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('46','Iran','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('47','Iraq','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('48','Israel','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('49','Italy','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('50','Japan','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('51','Kazakstan','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('52','Kenya','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('53','Kuwait','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('54','Latvia','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('55','Liechtenstein','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('56','Lithuania','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('57','Madagascar','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('58','Malawi','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('59','Malaysia','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('60','Mexico','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('61','Moldova','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('62','Morocco','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('63','Mozambique','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('64','Myanmar','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('65','Nauru','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('66','Nepal','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('67','Netherlands','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('68','New Zealand','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('69','Nigeria','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('70','North Korea','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('71','Oman','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('72','Pakistan','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('73','Paraguay','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('74','Peru','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('75','Philippines','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('76','Poland','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('77','Puerto Rico','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('78','Romania','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('79','Runion','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('80','Russian Federation','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('81','Saint Vincent and the Grenadines','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('82','Saudi Arabia','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('83','Senegal','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('84','Slovakia','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('85','South Africa','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('86','South Korea','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('87','Spain','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('88','Sri Lanka','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('89','Sudan','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('90','Sweden','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('91','Switzerland','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('92','Taiwan','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('93','Tanzania','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('94','Thailand','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('95','Tonga','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('96','Tunisia','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('97','Turkey','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('98','Turkmenistan','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('99','Tuvalu','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('100','Ukraine','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('101','United Arab Emirates','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('102','United Kingdom','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('103','United States','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('104','Venezuela','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('105','Vietnam','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('106','Virgin Islands, U.S.','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('107','Yemen','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('108','Yugoslavia','2006-02-15 04:44:00.000')
;
Insert into country
 (`country_id`,`country`,`last_update`)
Values
('109','Zambia','2006-02-15 04:44:00.000')
;
-- End of Script
--
--