USE sakila;
-- Automatically generated by Advanced ETl Processor
-- http://www.etl-tools.com/
-- table actor
-- Start of script
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('1','PENELOPE','GUINESS','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('2','NICK','WAHLBERG','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('3','ED','CHASE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('4','JENNIFER','DAVIS','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('5','JOHNNY','LOLLOBRIGIDA','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('6','BETTE','NICHOLSON','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('7','GRACE','MOSTEL','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('8','MATTHEW','JOHANSSON','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('9','JOE','SWANK','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('10','CHRISTIAN','GABLE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('11','ZERO','CAGE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('12','KARL','BERRY','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('13','UMA','WOOD','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('14','VIVIEN','BERGEN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('15','CUBA','OLIVIER','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('16','FRED','COSTNER','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('17','HELEN','VOIGHT','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('18','DAN','TORN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('19','BOB','FAWCETT','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('20','LUCILLE','TRACY','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('21','KIRSTEN','PALTROW','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('22','ELVIS','MARX','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('23','SANDRA','KILMER','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('24','CAMERON','STREEP','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('25','KEVIN','BLOOM','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('26','RIP','CRAWFORD','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('27','JULIA','MCQUEEN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('28','WOODY','HOFFMAN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('29','ALEC','WAYNE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('30','SANDRA','PECK','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('31','SISSY','SOBIESKI','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('32','TIM','HACKMAN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('33','MILLA','PECK','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('34','AUDREY','OLIVIER','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('35','JUDY','DEAN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('36','BURT','DUKAKIS','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('37','VAL','BOLGER','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('38','TOM','MCKELLEN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('39','GOLDIE','BRODY','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('40','JOHNNY','CAGE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('41','JODIE','DEGENERES','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('42','TOM','MIRANDA','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('43','KIRK','JOVOVICH','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('44','NICK','STALLONE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('45','REESE','KILMER','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('46','PARKER','GOLDBERG','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('47','JULIA','BARRYMORE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('48','FRANCES','DAY-LEWIS','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('49','ANNE','CRONYN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('50','NATALIE','HOPKINS','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('51','GARY','PHOENIX','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('52','CARMEN','HUNT','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('53','MENA','TEMPLE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('54','PENELOPE','PINKETT','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('55','FAY','KILMER','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('56','DAN','HARRIS','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('57','JUDE','CRUISE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('58','CHRISTIAN','AKROYD','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('59','DUSTIN','TAUTOU','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('60','HENRY','BERRY','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('61','CHRISTIAN','NEESON','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('62','JAYNE','NEESON','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('63','CAMERON','WRAY','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('64','RAY','JOHANSSON','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('65','ANGELA','HUDSON','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('66','MARY','TANDY','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('67','JESSICA','BAILEY','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('68','RIP','WINSLET','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('69','KENNETH','PALTROW','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('70','MICHELLE','MCCONAUGHEY','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('71','ADAM','GRANT','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('72','SEAN','WILLIAMS','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('73','GARY','PENN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('74','MILLA','KEITEL','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('75','BURT','POSEY','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('76','ANGELINA','ASTAIRE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('77','CARY','MCCONAUGHEY','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('78','GROUCHO','SINATRA','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('79','MAE','HOFFMAN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('80','RALPH','CRUZ','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('81','SCARLETT','DAMON','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('82','WOODY','JOLIE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('83','BEN','WILLIS','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('84','JAMES','PITT','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('85','MINNIE','ZELLWEGER','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('86','GREG','CHAPLIN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('87','SPENCER','PECK','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('88','KENNETH','PESCI','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('89','CHARLIZE','DENCH','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('90','SEAN','GUINESS','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('91','CHRISTOPHER','BERRY','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('92','KIRSTEN','AKROYD','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('93','ELLEN','PRESLEY','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('94','KENNETH','TORN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('95','DARYL','WAHLBERG','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('96','GENE','WILLIS','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('97','MEG','HAWKE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('98','CHRIS','BRIDGES','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('99','JIM','MOSTEL','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('100','SPENCER','DEPP','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('101','SUSAN','DAVIS','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('102','WALTER','TORN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('103','MATTHEW','LEIGH','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('104','PENELOPE','CRONYN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('105','SIDNEY','CROWE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('106','GROUCHO','DUNST','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('107','GINA','DEGENERES','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('108','WARREN','NOLTE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('109','SYLVESTER','DERN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('110','SUSAN','DAVIS','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('111','CAMERON','ZELLWEGER','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('112','RUSSELL','BACALL','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('113','MORGAN','HOPKINS','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('114','MORGAN','MCDORMAND','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('115','HARRISON','BALE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('116','DAN','STREEP','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('117','RENEE','TRACY','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('118','CUBA','ALLEN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('119','WARREN','JACKMAN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('120','PENELOPE','MONROE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('121','LIZA','BERGMAN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('122','SALMA','NOLTE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('123','JULIANNE','DENCH','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('124','SCARLETT','BENING','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('125','ALBERT','NOLTE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('126','FRANCES','TOMEI','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('127','KEVIN','GARLAND','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('128','CATE','MCQUEEN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('129','DARYL','CRAWFORD','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('130','GRETA','KEITEL','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('131','JANE','JACKMAN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('132','ADAM','HOPPER','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('133','RICHARD','PENN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('134','GENE','HOPKINS','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('135','RITA','REYNOLDS','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('136','ED','MANSFIELD','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('137','MORGAN','WILLIAMS','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('138','LUCILLE','DEE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('139','EWAN','GOODING','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('140','WHOOPI','HURT','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('141','CATE','HARRIS','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('142','JADA','RYDER','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('143','RIVER','DEAN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('144','ANGELA','WITHERSPOON','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('145','KIM','ALLEN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('146','ALBERT','JOHANSSON','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('147','FAY','WINSLET','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('148','EMILY','DEE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('149','RUSSELL','TEMPLE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('150','JAYNE','NOLTE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('151','GEOFFREY','HESTON','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('152','BEN','HARRIS','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('153','MINNIE','KILMER','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('154','MERYL','GIBSON','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('155','IAN','TANDY','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('156','FAY','WOOD','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('157','GRETA','MALDEN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('158','VIVIEN','BASINGER','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('159','LAURA','BRODY','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('160','CHRIS','DEPP','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('161','HARVEY','HOPE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('162','OPRAH','KILMER','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('163','CHRISTOPHER','WEST','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('164','HUMPHREY','WILLIS','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('165','AL','GARLAND','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('166','NICK','DEGENERES','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('167','LAURENCE','BULLOCK','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('168','WILL','WILSON','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('169','KENNETH','HOFFMAN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('170','MENA','HOPPER','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('171','OLYMPIA','PFEIFFER','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('172','GROUCHO','WILLIAMS','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('173','ALAN','DREYFUSS','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('174','MICHAEL','BENING','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('175','WILLIAM','HACKMAN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('176','JON','CHASE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('177','GENE','MCKELLEN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('178','LISA','MONROE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('179','ED','GUINESS','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('180','JEFF','SILVERSTONE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('181','MATTHEW','CARREY','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('182','DEBBIE','AKROYD','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('183','RUSSELL','CLOSE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('184','HUMPHREY','GARLAND','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('185','MICHAEL','BOLGER','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('186','JULIA','ZELLWEGER','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('187','RENEE','BALL','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('188','ROCK','DUKAKIS','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('189','CUBA','BIRCH','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('190','AUDREY','BAILEY','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('191','GREGORY','GOODING','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('192','JOHN','SUVARI','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('193','BURT','TEMPLE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('194','MERYL','ALLEN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('195','JAYNE','SILVERSTONE','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('196','BELA','WALKEN','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('197','REESE','WEST','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('198','MARY','KEITEL','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('199','JULIA','FAWCETT','2006-02-15 04:34:33.000')
;
Insert into actor
 (`actor_id`,`first_name`,`last_name`,`last_update`)
Values
('200','THORA','TEMPLE','2006-02-15 04:34:33.000')
;
-- End of Script
--
--