USE sakila;
-- Automatically generated by Advanced ETl Processor
-- http://www.etl-tools.com/
-- table store
-- Start of script
Insert into store
 (`store_id`,`manager_staff_id`,`address_id`,`last_update`)
Values
('1','1','1','2006-02-15 04:57:12.000')
;
Insert into store
 (`store_id`,`manager_staff_id`,`address_id`,`last_update`)
Values
('2','2','2','2006-02-15 04:57:12.000')
;
-- End of Script
--
--