USE sakila;
-- Automatically generated by Advanced ETl Processor
-- http://www.etl-tools.com/
-- table category
-- Start of script
Insert into category
 (`category_id`,`name`,`last_update`)
Values
('1','Action','2006-02-15 04:46:27.000')
;
Insert into category
 (`category_id`,`name`,`last_update`)
Values
('2','Animation','2006-02-15 04:46:27.000')
;
Insert into category
 (`category_id`,`name`,`last_update`)
Values
('3','Children','2006-02-15 04:46:27.000')
;
Insert into category
 (`category_id`,`name`,`last_update`)
Values
('4','Classics','2006-02-15 04:46:27.000')
;
Insert into category
 (`category_id`,`name`,`last_update`)
Values
('5','Comedy','2006-02-15 04:46:27.000')
;
Insert into category
 (`category_id`,`name`,`last_update`)
Values
('6','Documentary','2006-02-15 04:46:27.000')
;
Insert into category
 (`category_id`,`name`,`last_update`)
Values
('7','Drama','2006-02-15 04:46:27.000')
;
Insert into category
 (`category_id`,`name`,`last_update`)
Values
('8','Family','2006-02-15 04:46:27.000')
;
Insert into category
 (`category_id`,`name`,`last_update`)
Values
('9','Foreign','2006-02-15 04:46:27.000')
;
Insert into category
 (`category_id`,`name`,`last_update`)
Values
('10','Games','2006-02-15 04:46:27.000')
;
Insert into category
 (`category_id`,`name`,`last_update`)
Values
('11','Horror','2006-02-15 04:46:27.000')
;
Insert into category
 (`category_id`,`name`,`last_update`)
Values
('12','Music','2006-02-15 04:46:27.000')
;
Insert into category
 (`category_id`,`name`,`last_update`)
Values
('13','New','2006-02-15 04:46:27.000')
;
Insert into category
 (`category_id`,`name`,`last_update`)
Values
('14','Sci-Fi','2006-02-15 04:46:27.000')
;
Insert into category
 (`category_id`,`name`,`last_update`)
Values
('15','Sports','2006-02-15 04:46:27.000')
;
Insert into category
 (`category_id`,`name`,`last_update`)
Values
('16','Travel','2006-02-15 04:46:27.000')
;
-- End of Script
--
--