version: '3'
services:
  flyway:
    image: flyway/flyway
    command: migrate
    environment:
      FLYWAY_URL: jdbc:mysql://db
      FLYWAY_SCHEMAS: sakila
      FLYWAY_USER: root
      FLYWAY_PASSWORD: P@ssw0rd
      FLYWAY_CONNECT_RETRIES: 60
    volumes:
      - ./database/flyway:/flyway/sql
    depends_on:
      - db
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306